if melodyFiltCh ~= 4
filteredMelody =...
    filter(filters(melodyFiltCh),...
    filter(filters(melodyFiltCh),...
    filter(filters(melodyFiltCh),...
    song1.melody.voices(melodyVoiceCh,:)) ) );
else
    filteredMelody = song1.melody.voices(melodyVoiceCh,:);
end
if bassFiltCh ~= 4
filteredBass =...
    filter(filters(bassFiltCh),...
    filter(filters(bassFiltCh),...
    filter(filters(bassFiltCh),...
    song1.bass.voices(bassVoiceCh,:)) ) );
else
    filteredBass = song1.bass.voices(bassVoiceCh,:);
end
melodyAndBass = zeros(1,song1.lengthSamples);

for i = 1:song1.lengthSamples
    melodyAndBass(i) = ( filteredMelody(i) +...
                         filteredBass(i)        ) /2;
end


songTwice = [melodyAndBass melodyAndBass];

